### ISSUE TITLE
API error.

### ISSUE THREAD

**Issue by hisashiyamaguchi** [auth0-blog/auth0-restful-dashboard#1]
Hi

I'm trying to run the code with referring README, and my API gets an error. Here comes the error.

listening on port 3001
(node:19681) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getClients' of undefined
    at Object.getClients (/Users/hisashiyamaguchi/auth0-restful-dashboard/auth0-restful-management-api/Auth0Manager.js:102:14)
    at getClients (/Users/hisashiyamaguchi/auth0-restful-dashboard/auth0-restful-management-api/index.js:55:40)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:19681) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:19681) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

My testing environment is below.

OS : macOS Mojave 10.14.6
node : 10.15.3
npm : 6.11.3

Hisashi Yamaguchi
Auth0 Japan team

**Comment by noid999** [comment]
Hi me too, wasted a lot of time to fix but no luck. Makes me angry.
